version: "3.8"
services:
  web:
    image: consomme:latest
    ports:
      - "3001:3000"
  redis:
    image: "redis:alpine"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: consomme
      POSTGRES_USER: consomme_user
      POSTGRES_PASSWORD: consomme_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  kafka:
    image: "spotify/kafka:latest"
    environment:
      ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
      - "2181:2181"
